apiVersion: v1
kind: Pod
metadata:
  name: multicon
spec:
   selector:
   containers:
      - name:  ngnx   
        image: nginx:alpine
        ports:
          - containerPort: 8080
            protocol:   TCP
      - name:  mycv
        image: mehrjay86/mycv
        ports: 
         - containerPort: 8081
           protocol: TCP
  ---
  apiVersion: v1
kind: Service
metadata:
  name: mcon
spec:
  type: NodePort
  ports:
   - name: http 
     targetPort: 8080
     port: 80
   - name : https
     targetPort: 8443
     port: 443
  selector:
    app: multicon
   
          
